INSERT INTO kbli (no_kbli, keterangan)
  VALUES ("01","Pertanian Tanaman, Peternakan, Perburuan dan Kegiatan YBDI"),
   ("02","Pengelolaan Kehutanan dan Penebangan"),
    ("03","Perikanan"),
     ("05","Pertambangan Batu Bara dan Lignit"),
      ("06","Pertambangan Minyak Bumi dan Gas Alam dan Panas Bumi"),
       ("07","Pertambangan Bijih Logam"),
        ("08","Pertambangan dan Penggalian Lainnya"),
         ("09","Aktivitas Jasa Penunjang Pertambangan"),
          ("10","Industri Makanan"),
           ("11","Industri Minuman"),
            ("12","Industri Pengolahan Tembakau"),
             ("13","Industri Tekstil"),
              ("14","Industri Pakaian Jadi"),
               ("15","Industri Kulit, Barang dari Kulit dan Alas
Kaki"),
                ("16","Industri Kayu, Barang dari Kayu dan Gabus (Tidak Termasuk Furnitur) dan Barang Anyaman dari Bambu, Rotan
dan Sejenisnya"),
                 ("17","Industri Kertas dan Barang dari Kertas"),
                 ("18","Industri Pencetakan dan Reproduksi
Media Rekaman"),
                 ("19","Industri Produk Dari Batu Bara dan Pengilangan Minyak Bumi"),
                 ("20","Industri Bahan Kimia dan Barang dari Bahan Kimia"),
                 ("21","Industri Farmasi, Produk Obat Kimia dan Obat Tradisional"),
                 ("22","Industri Karet, Barang dari Karet dan Plastik"),
                 ("23","Industri Barang Galian Bukan Logam"),
                 ("24","Industri Logam Dasar"),
                 ("25","Industri Barang Logam, Bukan Mesin
dan Peralatannya"),
                 ("26","Industri Komputer, Barang Elektronik dan Optik"),
                 ("27","Industri Peralatan Listrik"),
                 ("28","Industri Mesin dan Perlengkapan ytdl"),
                 ("29","Industri Kendaraan Bermotor, Trailer dan Semi Trailer"),
                 ("30","Industri Alat Angkutan Lainnya"),
                 ("31","Industri Furnitur"),
                 ("32","Industri Pengolahan Lainnya"),
                 ("33","Reparasi dan Pemasangan Mesin dan Peralatan"),
                 ("35","Pengadaan Listrik, Gas, Uap/Air Panas dan Udara Dingin"),
                 ("36","Treatment Air"),
                 ("37","Treatment Air Limbah"),
                 ("38","Pengumpulan, Treatment dan Pembuangan Limbah dan Sampah Serta
Aktivitas Pemulihan Material"),
                 ("39","Aktivitas Remediasi dan Pengelolaan Limbah dan Sampah Lainnya"),
                 ("41","Konstruksi Gedung"),
                 ("42","Konstruksi Bangunan Sipil"),
                 ("43","Konstruksi Khusus"),
                 ("45","Perdagangan, Reparasi dan Perawatan
Mobil dan Sepeda Motor"),
                 ("46","Perdagangan Besar, Bukan Mobil dan Sepeda Motor"),
                 ("47","Perdagangan Eceran, Bukan Mobil dan Motor"),
                 ("49","Angkutan Darat dan Angkutan Melalui Saluran Pipa"),
                 ("50","Angkutan Perairan"),
                 ("51","Angkutan Udara"),
                 ("52","Pergudangan dan Aktivitas Penunjang Angkutan"),
                 ("53","Aktivitas Pos dan Kurir"),
                 ("55","Penyediaan Akomodasi"),
                 ("56","Penyediaan Makanan dan Minuman"),
                 ("58","Aktivitas Penerbitan"),
                 ("59","Aktivitas Produksi Gambar Bergerak, Video dan Program Televisi, Perekaman Suara dan Penerbitan Musik"),
                 ("60","Aktivitas Penyiaran dan Pemrograman"),
                 ("61","Telekomunikasi"),
                 ("62","Aktivitas Pemrograman, Konsultasi
Komputer dan Kegiatan Ybdi"),
                 ("63","Aktivitas Jasa Informasi"),
                 ("64","Aktivitas Jasa Keuangan, Bukan Asuransi dan Dana Pensiun"),
                 ("65","Asuransi, Penjaminan, Reasuransi dan Dana Pensiun, Bukan Jaminan Sosial
Wajib"),
                 ("66","Aktivitas Penunjang Jasa Keuangan, Asuransi, Penjaminan dan Dana Pensiun"),
                 ("68","Real Estat"),
                 ("69","Aktivitas Hukum dan Akuntansi"),
                 ("70","Aktivitas Kantor Pusat dan Konsultasi Manajemen"),
                 ("71","Aktivitas Arsitektur dan Keinsinyuran,
Analisis dan Uji Teknis"),
                 ("72","Penelitian dan Pengembangan Ilmu
Pengetahuan"),
                 ("73","Periklanan dan Penelitian Pasar"),
                 ("74","Aktivitas Profesional, Ilmiah dan Teknis Lainnya"),
                 ("75","Aktivitas Kesehatan Hewan"),
                 ("77","Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi"),
                 ("78","Aktivitas Ketenagakerjaan"),
                 ("79","Aktivitas Agen Perjalanan, Penyelenggara Tur dan Jasa Reservasi Lainnya"),
                 ("80","Aktivitas Keamanan dan Penyelidikan"),
                 ("81","Aktivitas Penyedia Jasa untuk Gedung dan Pertamanan"),
                 ("82","Aktivitas Administrasi Kantor, Aktivitas Penunjang Kantor dan Aktivitas Penunjang Usaha Lainnya"),
                 ("84","Administrasi Pemerintahan, Pertahanan dan Jaminan Sosial Wajib"),
                 ("85","Pendidikan"),
                 ("86","Aktivitas Kesehatan Manusia"),
                 ("87","Aktivitas Sosial di Dalam Panti"),
                 ("88","Aktivitas Sosial Tanpa Akomodasi"),
                 ("90","Aktivitas Hiburan, Kesenian dan Kreativitas"),
                 ("91","Perpustakaan, Arsip, Museum dan Kegiatan Kebudayaan Lainnya"),
                 ("92","Aktivitas Perjudian dan Pertaruhan"),
                 ("93","Aktivitas Olahraga dan Rekreasi Lainnya"),
                 ("94","Aktivitas Keanggotaan Organisasi"),
                 ("95","Reparasi Komputer dan Barang Keperluan Pribadi dan Perlengkapan
Rumah Tangga"),
                 ("96","Aktivitas Jasa Perorangan Lainnya"),
                 ("97","Aktivitas Rumah Tangga Sebagai Pemberi Kerja Dari Personil Domestik"),
                 ("98","Aktivitas Yang Menghasilkan Barang dan Jasa oleh Rumah Tangga Yang Digunakan untuk Memenuhi Kebutuhan
Sendiri"),
                 ("99","Aktivitas Badan Internasional dan Badan Ekstra Internasional Lainnya");
               